import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function MyPage() {
  const [user, setUser] = useState("");

  useEffect(() => {
    fetch("/.auth/me")
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setUser(data?.clientPrincipal?.userDetails);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Next Azure App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>こんにちは、{user} さん!</h1>
        <a href="/logout?post_logout_redirect_uri=/">ログアウト</a>
      </main>
    </>
  );
}
