import styles from "@/styles/Home.module.css";
import { Message } from "@/types/Message";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [message, setMessage] = useState<Array<Message>>([]);
  useEffect(() => {
    fetch("/api/GetAllMessage")
      .then((res) => res.json())
      .then((data) => {
        setMessage(data);
        console.log("GetAllMessage:", data);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <header>
          <div>
            <a href="/login?post_login_redirect_uri=/">Login</a>
          </div>
          <div>
            <a href="/mypage">mypage</a>
          </div>
        </header>
        <div>
          {message?.map((t) => (
            <div key={t.RowKey} className={`${styles.message}`}>
              <div>
                <b>@{t.PartitionKey}</b>
              </div>
              <div>{t.Message}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
